### ISSUE TITLE
コードのMVC化

### ISSUE THREAD

**Issue by kiekobayashi** [kiekobayashi/babyfood_store#1]
自身のECサイトのMVC化を進めます。

**Comment by kiekobayashi** [comment]
@primestyleus login_processing.phpが正しく動くよう変更してみたのですが、
[Warning: session_start(): Cannot start session when headers already sent in /var/www/html/login_processing.php on line 6]
[Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/login_processing.php:1) in /var/www/model/functions.php on line 9]
この二つのエラーが出てしまいます。色々と調べて調整してみたのですが、エラーが変わらない為一度見ていただくことは可能でしょうか？VSCodeの方でコミットをしてみたのですが、こちらでご確認いただけますか？

**Comment by primestyleus** [comment]
@kiekobayashi 
そうですね、「functions.php on line 9」の部分でエラーとなっているようですね。
ただ、コードがまだPUSHされていないようでして、GitHub上ではまだ確認ができないので、PUSHしていただけますか？

**Comment by kiekobayashi** [comment]
@primestyleus 
正しくPUSHができていなかったようです。再度実施いたしました。

**Comment by primestyleus** [comment]
@kiekobayashi 

このエラーはすでにHTMLが出力されたあとにsession_startなどをするとおこるエラーです。
login_processing.phpの1行目におそらくスペースが先頭に入ってしまっているのが原因ではないかと思います。
` <?php`
スペース消して試していただけますか？

**Comment by kiekobayashi** [comment]
@primestyleus 
気付きませんでした、ありがとうございました！元のエラーは解消しましたが、現在はログインができず苦戦しています。

**Comment by kiekobayashi** [comment]
@primestyleus 
現在adminでログインした後の商品管理画面を修正しています。
商品のステータス変更や在庫数変更は行えるのですが、商品を新規で登録する際に「価格は0以上の整数で入力してください」のエラーメッセージが毎回出てしまい、登録することができません。
原因を探しているのですがなかなか見つからず、一度ご確認いただくことは可能でしょうか？
よろしくお願いいたします。

**Comment by primestyleus** [comment]
@kiekobayashi 

MVC化、けっこう進んでいるようですね！
「validate_item」関数ですが、定義箇所と実行箇所で引数の数が一致していないようです。
（定義のほうに$commentが漏れている？）

**Comment by kiekobayashi** [comment]
@primestyleus 
こんにちは。MVC化を進めているのですが、購入を完了すると同じ商品購入履歴が二回登録されてしまいます。誤りを探しているのですが見つからない為、一度ご確認いただけますでしょうか？

**Comment by primestyleus** [comment]
@kiekobayashi 

コードを見る限りは問題なさそうなので動かしながら確認をしてみたいのですが、DBをエクスポートしていただき、lamp_dockの下に、エクスポートしたSQLのファイルを追加してcommit & push いただくことは可能でしょうか？

**Comment by kiekobayashi** [comment]
@primestyleus 
ありがとうございます。check_history.sqlという名前のファイルに追加しました。ご確認のほどよろしくお願い致します。

**Comment by primestyleus** [comment]
@kiekobayashi 

finish_view.phpの14行目でpurchase_cartsが再度実行されてしまっているようですね。
    <?php if (purchase_carts($db, $carts) === true) { ?>

こちらを別の方法で判定するようにしてみてください！

**Comment by kiekobayashi** [comment]
@primestyleus 
確認後修正いたしました。
ありがとうございます！

**Comment by kiekobayashi** [comment]
@primestyleus 
 昨日授業で指摘を受けた部分を修正いたしました。トップ画面にて商品画像をクリックすると、正しく商品情報が表示されるようになったのですが、そこで「カートに入れる」ボタンを押すとdetail.phpのURLに飛んでしまい、商品情報が正しく表示されなくなってしまいます。元のdetail.php?id=[商品ID]の画面に飛ぶようにするために色々試したのですが、うまくいきません。一度ご確認いただいてもよろしいでしょうか？

**Comment by primestyleus** [comment]
@kiekobayashi 

カートに入れるときに商品IDをhiddenで飛ばしていると思いますので、カートに入れる処理が一通り終わったら、そのままViewを表示するのでなく、リダイレクトをすると良いかと思います。そのときに、detail.php?id=[hiddenで飛ばされた商品ID]の形にしてみてください。

**Comment by kiekobayashi** [comment]
@primestyleus 
「redirect_to('detail.php?id=' . $item_id);」こちらで解決しました！
ありがとうございます。

**Comment by kiekobayashi** [comment]
@primestyleus 
何度も申し訳ありません。現在月齢別の商品一覧画面も作成しひと段落したのですが、top.phpまたはage.phpにて同じ商品の「カートに入れる」ボタンを数回押した際、きちんとカート内の数量が増える時と増えない時があることがわかりました。model/cart.phpを確認しているのですが原因がわからず、こちら一度ご確認いただいてもよろしいでしょうか？

**Comment by primestyleus** [comment]
@kiekobayashi 

こちら、原因を見つけるのに時間かかってしまいましたが、update_cart_amount関数にわたすのはitem_idではなくid(cartsテーブルの主キー)なので、UPDATEもidにする必要があります！

**Comment by kiekobayashi** [comment]
@primestyleus 
解決しました、ありがとうございます！
こちら、自分でも違和感があったのですが混乱してそのままになっていました…

**Comment by kiekobayashi** [comment]
@primestyleus 
こんばんは。明日の授業なのですが現在思うように課題が進められておらず、もう少し自分で進めてから色々と質問をさせていただきたいため、日にちを変更することは可能でしょうか？27.28日あたりであればありがたいのですが、ご確認いただけますと幸いです。申し訳ありません。

**Comment by primestyleus** [comment]
@kiekobayashi はい、27, 28いずれも大丈夫です!

**Comment by kiekobayashi** [comment]
@primestyleus
ありがとうございます！では、27の22時にお願いしてもよろしいでしょうか？

**Comment by primestyleus** [comment]
@kiekobayashi はい、空いてますので予約入れていただけれと思います

**Comment by kiekobayashi** [comment]
@primestyleus 
予約を入れさせていただきました。よろしくお願い致します。

**Comment by kiekobayashi** [comment]
@primestyleus 
こんばんは。CSRF対策の実装をしました。確認はしたので漏れはないかと思うのですが、一度ご確認いただきたいです。よろしくお願い致します。

**Comment by primestyleus** [comment]
@kiekobayashi 

細かな動作確認まではしていませんが、見た限り問題ないかと思います！
